init {
    DATABASE_USERNAME -> global.params.DATABASE_USERNAME;
    DATABASE_PASSWORD -> global.params.DATABASE_PASSWORD;
    DATABASE_HOST -> global.params.DATABASE_HOST;
    DATABASE_BASE -> global.params.DATABASE_BASE;
    DATABASE_DRIVER -> global.params.DATABASE_DRIVER
}
